### ISSUE TITLE
The link hints are too crowded.

### ISSUE THREAD

**Issue by ahloiscreamo** [AlfredoSequeida/hints#1]
Hello,

So i just install it to give it a try, it doesn't look like expected.

when i run on terminal, error output 

`~ 
❯ hints

(hints:29251): Gtk-WARNING **: 21:05:38.326: Theme parsing error: gtk.css:1410:11: '' is not a valid color name

(hints:29251): Gtk-WARNING **: 21:05:38.330: Theme parsing error: gtk.css:3159:9: '' is not a valid color name`

![Screenshot from 2024-12-30 21-08-53](https://github.com/user-attachments/assets/1e78c7fb-99f6-4902-997f-3fd1e53ceb74)

**Comment by AlfredoSequeida** [comment]
Hey, looks like you're the first. So this is because this application is using the opencv backend. [more information here](https://github.com/AlfredoSequeida/hints/wiki/Configuration-guide#backends). 

What applications is this? You will likely need to follow the accessibility setup instructions is the README or the information in the wiki for extra setup.

**Comment by ahloiscreamo** [comment]
Thanks for the fast response, the app on question are firefox.
 
allright, let me check on that. I will be back should i need more help.

**Comment by ahloiscreamo** [comment]
Hey it work now, like it should.
I just need to exported env `GNOME_ACCESSIBILITY=1` on /etc/environment
![Screenshot from 2024-12-30 23-18-04](https://github.com/user-attachments/assets/ff817a5a-6daa-4ec9-8691-2153bb6a0a2b)

I will close the issue.

**Comment by d0dgi** [comment]
any other possible solution to this seems im having the exact issue but the environment isnt solving it...
![hints](https://github.com/user-attachments/assets/0b818d16-8145-4f50-844d-f0a000c9f60b)
![environment](https://github.com/user-attachments/assets/d35ecdf6-2efe-4f7a-ae29-4c0258a963f6)

**Comment by TheCedarPrince** [comment]
I am also running into this same issue @d0dgi

**Comment by AlfredoSequeida** [comment]
@d0dgi what app is that?

**Comment by AlfredoSequeida** [comment]
@TheCedarPrince @d0dgi What application(s) are you seeing this on? For chromium based apps there is information in the wiki for other things you need to do.

**Comment by d0dgi** [comment]
I am running some snaps but not this one (Vivaldi) it's chromium and I was able to get it to work with using accercisor. Only downside is I have to validate the affected apps (Vivaldi, Signal messenger for example) with accercisor every time they open for them to work properly rn.

**Comment by AlfredoSequeida** [comment]
@d0dgi since they are Chromium apps you will need to launch them with the `--force-renderer-accessibility` flag. If you want to make this parmanent you can edit your desktop files for those apps to include that flag in the exec command.

**Comment by TheCedarPrince** [comment]
Ah! I thought I had accessibility all set but the force accessibility flag fixed things for me just fine. Thanks @AlfredoSequeida !
